# ------------------------------------------------------------------------------
#   This is a problem for the onlinejudge platform. It is a single file that
#   represents the description, initial code, and unit tests for a single
#   problem.
#   
#   It is written in TOML. Please read: https://github.com/toml-lang/toml
#
#   To validate please execute:
#
#   go get github.com/BurntSushi/toml/cmd/tomlv
#   tomlv <path to TOML file>
# ------------------------------------------------------------------------------

# Do not change id once a problem is uploaded.
Id = "split_console_output_part_1"

# Increment version every time you want to re-upload a problem. You should
# probably update last_updated_date if you increment the version.
Version = 1

Title = "Split Console Output (Part 1)"
Category = "Strings"
SupportedLanguages = [
    "java",
    "python",
]
CreationDate = 2015-07-20T00:00:00Z
LastUpdatedDate =  2015-07-20T00:00:00Z

# ------------------------------------------------------------------------------
# This is Markdown. To preview it use something like http://dillinger.io/.
#
# If you want one description for all languages specify a [Description._all]
# section. If there are language-specific descriptions, e.g.
# [Description.java] they will be used in preference to _all if it exists.
# ------------------------------------------------------------------------------
[Description]

[Description._all]
markdown = '''
## Split Console Output (Part 1)

### Description

We need to print out log statements that can fit inside a terminal window.
We'd like a reusable function to do so. Hence, given a log message string
and a column number break the log message on word boundaries and return a list
of lines you'd print out.

### Examples

-   `("this is a log message", 7)` would return `["this is", "a log", "message"]`
'''
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Initial code is presented to the user at the start of the problem. It should
# give them the function signature (or, if the function signature gives away
# the problem, sufficient language-specific comments to understand what is
# required).
# ------------------------------------------------------------------------------
[InitialCode]

[InitialCode.python]
code = '''
def split_console_output_part_1(input, columns):
    return [""]
'''

[InitialCode.java]
code = '''
import java.util.*;
import java.io.*;

public class Solution {
    public static List<String> splitConsoleOutputPart1(final String input, final int columns) {
        return new ArrayList<>();
    }
}
'''
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Unit tests are used by the server to verify the validity of answers.
# - Their code is never revealed to the user.
# - Their stdout must not reveal the inputs used in tests.
# - Their stdout may reveal the outputs used in tests (just like normal unit
#   tests).
#
# Code is written out to one file, unit tests to another, and the two files are
# compiled (if necessary) then the unit test file is executed. The names are:
# - Java: Solution.java / SolutionTest.java
# - Python: foo.py / foo_test.py
#
# How we run in each language:
#
# - Java:
#   javac -cp '.:/tmp/junit-4.12.jar:/tmp/hamcrest-core-1.3.jar' Solution.java SolutionTest.java
#   java -cp '.:/tmp/junit-4.12.jar:/tmp/hamcrest-core-1.3.jar' SolutionTest
#   (need junit and hamcrest JARs)
#
# - Python:
#   python foo_test.py
# ------------------------------------------------------------------------------
[UnitTest]

[UnitTest.java]
code = '''
import java.util.*;
import java.io.*;
import org.junit.*;
import static org.junit.Assert.*;

public class SolutionTest {
    @Test
    public void test1() {
        assertEquals(Arrays.asList("this is", "a log", "message"),
            Solution.splitConsoleOutputPart1("this is a log message", 7));
    }

    public static void main(String[] args) {
        org.junit.runner.JUnitCore.main("SolutionTest");
    }
}
'''

[UnitTest.python]
code = '''
import unittest

import foo


class TestSplitConsoleOutputPart1(unittest.TestCase):
    def test1(self):
        self.assertEqual(['this is', 'a log', 'message'],
                         foo.split_console_output_part_1('this is a log message', 7))

if __name__ == '__main__':
    unittest.main(verbosity=2)
'''
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# When we first launch there won't by any solutions. These solutions will seed
# the voted list of solutions (might not be the best solutions!)
# ------------------------------------------------------------------------------
[Approach]

[Approach._all]
markdown = '''
'''

[Solution]

[Solution.java]
code = '''
import java.util.*;
import java.io.*;

public class Solution {
    public static List<String> splitConsoleOutputPart1(final String input, final int columns) {
        return new ArrayList<>();
    }
}
'''

[Solution.python]
code = '''
import itertools


def update_current_line_and_result(current_line, current_word, result, columns):
    if len(current_word) + len(current_line) <= columns:
        current_line += current_word + " "
    else:
        result.append(current_line[:-1])
        current_line = current_word + " "
    return current_line


def split_console_output_part_1(input, columns):
    result = []
    current_word = ""
    current_line = ""
    for character in input:
        if character == " " and len(current_word) != 0:
            current_line = update_current_line_and_result(current_line, current_word, result, columns)
            current_word = ""
        else:
            current_word += character
    current_line = update_current_line_and_result(current_line, current_word, result, columns)
    result.append(current_line[:-1])
    return result
'''
# ------------------------------------------------------------------------------
